import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col")}>
        <header className="border-b">
          <div className="flex h-16 items-center px-4">
            <nav className="flex items-center space-x-4 lg:space-x-6 mx-6">
              <Link
                href="/overview"
                className="text-sm font-medium text-gray-400 transition-colors hover:text-gray-700"
              >
                Overview
              </Link>
              <Link
                href="/customers"
                className="text-sm font-medium text-gray-400 transition-colors hover:text-gray-700"
              >
                Customers
              </Link>
              <Link
                href="/products"
                className="text-sm font-medium text-gray-400 transition-colors hover:text-gray-700"
              >
                Products
              </Link>
              <Link
                href="/settings"
                className="text-sm font-medium text-gray-400 transition-colors hover:text-gray-700"
              >
                Settings
              </Link>
            </nav>
            <div className="ml-auto flex items-center space-x-4">Login</div>
          </div>
        </header>
        <main className="flex-1 space-y-4 p-8 pt-6">{children}</main>
      </body>
    </html>
  );
}
